name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --------------------------------------------------------

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      # --------------------------------------------------------

      - name: Install dependencies
        run: npm ci

      - name: Run Node.js tests
        run: npm run test:root

      - name: Run build
        run: npm run build

      - name: Run benchmarks
        run: |
          echo "🚀 Running async-primitives benchmarks..."
          echo "=========================================="
          npm run benchmark
          echo "=========================================="
          echo "✅ Benchmark completed!"

  browser-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run browser tests
        run: npm run test:browser

  build:
    runs-on: ubuntu-latest
    needs: [test, browser-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --------------------------------------------------------

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      # --------------------------------------------------------

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Check build output
        run: |
          ls -la dist/
          test -f dist/index.js
          test -f dist/index.cjs
          test -f dist/index.d.ts
